---
apiVersion: batch/v1
kind: Job
metadata:
  name: load-ny-taxi-data
spec:
  template:
    spec:
      containers:
        - name: load-ny-taxi-data
          image: "bitnami/minio:2022-debian-10"
          # yamllint disable-line rule:line-length
          command:
            - "bash"
            - "-ce"
            - |
              cd /tmp
              for month in 2020-09 2020-10 2020-11 2020-12; do
                curl -O https://repo.stackable.tech/repository/misc/ny-taxi-data/fhvhv_tripdata_$month.parquet
                mc alias set minio https://minio.default.svc.cluster.local:9000/ $(cat /minio-s3-credentials/accessKey) $(cat /minio-s3-credentials/secretKey)
                mc cp fhvhv_tripdata_$month.parquet minio/demo/ny-taxi-data/raw/
                mc mb --ignore-existing minio/prediction;
              done
          volumeMounts:
            - name: minio-s3-credentials
              mountPath: /minio-s3-credentials
            - name: tls
              mountPath: /.mc/certs/CAs
      volumes:
        - name: minio-s3-credentials
          secret:
            secretName: minio-s3-credentials
        - name: tls
          ephemeral:
            volumeClaimTemplate:
              metadata:
                annotations:
                  secrets.stackable.tech/class: tls
                  secrets.stackable.tech/scope: |-
                    service=minio
              spec:
                storageClassName: longhorn
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: "1"
      restartPolicy: OnFailure
  backoffLimit: 50
