FROM oci.stackable.tech/sdp/nifi:1.27.0-stackable0.0.0-dev

RUN curl --fail -o /stackable/nifi/postgresql-42.6.0.jar "https://repo.stackable.tech/repository/misc/postgresql-timescaledb/postgresql-42.6.0.jar"
