---
apiVersion: batch/v1
kind: Job
metadata:
  name: load-test-data
spec:
  template:
    spec:
      containers:
        - name: load-ny-taxi-data
          image: oci.stackable.tech/sdp/hadoop:3.4.1-stackable0.0.0-dev
          # yamllint disable rule:line-length
          command: ["bash", "-c", "/stackable/hadoop/bin/hdfs dfs -mkdir -p /ny-taxi-data/raw \
          && cd /tmp \
          && for month in 2020-09; do \
            curl -O https://repo.stackable.tech/repository/misc/ny-taxi-data/fhvhv_tripdata_$month.parquet \
            && /stackable/hadoop/bin/hdfs dfs -put fhvhv_tripdata_$month.parquet /ny-taxi-data/raw/; \
          done"]
          # yamllint enable rule:line-length
          volumeMounts:
            - name: hdfs-discovery-configmap
              mountPath: /hdfs
          env:
            - name: HADOOP_CONF_DIR
              value: /hdfs
      volumes:
        - name: hdfs-discovery-configmap
          configMap:
            name: hdfs-namenode-default
      restartPolicy: OnFailure
  backoffLimit: 50
